2024d12 (213/18)
One incorrect submission on part 2 - I should have seen that the output
on the sample input was incorrect before submitting, but my eyes are tired.

A few problems with how I wanted to use bfs vs. how it is required to be used.
I should fix that in the library.

	$ python day12.py -c
	Guessing paste kind from your clipboard metadata...
	Getting data from clipboard...
	Storing clipboard contents as inputs/day12-samp.txt...
	=============> inputs/day12-samp.txt <=============
	Traceback (most recent call last):
	  File "/kattis/aoc/aoc2024/day12.py", line 8, in <module>
	    if mat.bfs.enqueue(start):
	       ^^^^^^^^^^^^^^^^^^^^^^
	  File "/kattis/aoc/aoc2024/aoc.py", line 159, in enqueue
	    assert 1 <= self._i <= len(self._bfs)
			^^^^^^^
	AttributeError: 'Bfs' object has no attribute '_i'
	$ python day12.py -c
	Guessing paste kind from your clipboard metadata...
	Getting data from clipboard...
	Input 'samp' already exists at inputs/day12-samp.txt
	=============> inputs/day12-samp.txt <=============
	Traceback (most recent call last):
	  File "/kattis/aoc/aoc2024/day12.py", line 9, in <module>
	    if mat.bfs.enqueue(start):
	       ^^^^^^^^^^^^^^^^^^^^^^
	  File "/kattis/aoc/aoc2024/aoc.py", line 159, in enqueue
	    assert 1 <= self._i <= len(self._bfs)
		   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	AssertionError
	$ python day12.py -c
	Guessing paste kind from your clipboard metadata...
	Getting data from clipboard...
	Input 'samp' already exists at inputs/day12-samp.txt
	=============> inputs/day12-samp.txt <=============
	1930
	$ python day12.py -c
	Guessing paste kind from your clipboard metadata...
	Getting data from clipboard...
	Storing clipboard contents as inputs/day12-test.txt...
	=============> inputs/day12-samp.txt <=============
	1930
	=============> inputs/day12-test.txt <=============
	1424006
	$ python day12.py -c
	=============> inputs/day12-samp.txt <=============
	1930
	1930
	=============> inputs/day12-test.txt <=============
	1424006
	1424006
	$ python day12.py -c
	=============> inputs/day12-samp.txt <=============
	1930
	1616
	=============> inputs/day12-test.txt <=============
	1424006
	1206046
	$ python day12.py -p
	Guessing paste kind from your clipboard metadata...
	Getting data from clipboard...
	Storing clipboard contents as inputs/day12-samp2.txt...
	=============> inputs/day12-samp2.txt <=============
	1184
	960
	=============> inputs/day12-samp.txt <=============
	1930
	1616
	=============> inputs/day12-test.txt <=============
	1424006
	1206046
	$ python day12.py
	=============> inputs/day12-samp2.txt <=============
	1184
	1184
	=============> inputs/day12-samp.txt <=============
	1930
	1930
	=============> inputs/day12-test.txt <=============
	1424006
	1424006
	$ python day12.py
	=============> inputs/day12-samp2.txt <=============
	1184
	1184
	=============> inputs/day12-samp.txt <=============
	1930
	1930
	=============> inputs/day12-test.txt <=============
	1424006
	1424006
	$ python day12.py
	=============> inputs/day12-samp2.txt <=============
	1184
	368
	=============> inputs/day12-samp.txt <=============
	1930
	1206
	=============> inputs/day12-test.txt <=============
	1424006
	858684
	$ python day12.py -c
	=============> inputs/day12-samp2.txt <=============
	1184
	368
	=============> inputs/day12-samp.txt <=============
	1930
	1206
	=============> inputs/day12-test.txt <=============
	1424006
	858684