2024d4 (1097/572)
Using the string matrix in aoc.py led me astray
because I started using BFS for something that didn't require BFS at all.

	$ python3 day4.py -c
	Guessing paste kind from your clipboard metadata...
	Getting data from clipboard...
	Storing clipboard contents as inputs/day4-samp.txt...
	=============> inputs/day4-samp.txt <=============
	Traceback (most recent call last):
	  File "/kattis/aoc/aoc2024/day4.py", line 10, in <module>
	    mat.enqueue(a)
	    ^^^^^^^^^^^
	AttributeError: 'TupleStringMatrix' object has no attribute 'enqueue'
	$ python3 day4.py -c
	Guessing paste kind from your clipboard metadata...
	Getting data from clipboard...
	Input 'samp' already exists at inputs/day4-samp.txt
	=============> inputs/day4-samp.txt <=============
	0

(...snip some debugging...)

	$ python3 day4.py -c
	Guessing paste kind from your clipboard metadata...
	Unknown text pasted - continuing with previous sample input data
	=============> inputs/day4-samp.txt <=============
	START (0, 2)
	(0, 2) X 0
	Traceback (most recent call last):
	  File "/kattis/aoc/aoc2024/day4.py", line 12, in <module>
	    for n in mat.bfs.neigh4inside(a):
		     ^^^^^^^^^^^^^^^^^^^^
	AttributeError: 'Bfs' object has no attribute 'neigh4inside'

(...snip more printf-debugging...)

	$ python3 day4.py -c
	Guessing paste kind from your clipboard metadata...
	Unknown text pasted - continuing with previous sample input data
	=============> inputs/day4-samp.txt <=============
	5
	=============> inputs/day4-samp2.txt <=============
	14
	$ python3 day4.py -c
	Guessing paste kind from your clipboard metadata...
	Unknown text pasted - continuing with previous sample input data
	=============> inputs/day4-samp.txt <=============
	10
	=============> inputs/day4-samp2.txt <=============
	239
	$ python3 day4.py -c
	Guessing paste kind from your clipboard metadata...
	Unknown text pasted - continuing with previous sample input data
	=============> inputs/day4-samp.txt <=============
	Traceback (most recent call last):
	  File "/kattis/aoc/aoc2024/day4.py", line 5, in <module>
	    for n in cmat.neigh8(s):
		     ^^^^^^^^^^^
	AttributeError: 'ComplexStringMatrix' object has no attribute 'neigh8'
	=============> inputs/day4-samp2.txt <=============
	Traceback (most recent call last):
	  File "/kattis/aoc/aoc2024/day4.py", line 5, in <module>
	    for n in cmat.neigh8(s):
		     ^^^^^^^^^^^
	AttributeError: 'ComplexStringMatrix' object has no attribute 'neigh8'
	$ python3 day4.py -c
	Guessing paste kind from your clipboard metadata...
	Unknown text pasted - continuing with previous sample input data
	=============> inputs/day4-samp.txt <=============
	Traceback (most recent call last):
	  File "/kattis/aoc/aoc2024/day4.py", line 5, in <module>
	    for n in cmat.neigh8(s):
		     ^^^^^^^^^^^^^^
	  File "/kattis/aoc/aoc2024/aoc.py", line 242, in neigh8
	    row = int(pos.imag)
		      ^^^
	NameError: name 'pos' is not defined. Did you mean: 'os'?
	=============> inputs/day4-samp2.txt <=============
	Traceback (most recent call last):
	  File "/kattis/aoc/aoc2024/day4.py", line 5, in <module>
	    for n in cmat.neigh8(s):
		     ^^^^^^^^^^^^^^
	  File "/kattis/aoc/aoc2024/aoc.py", line 242, in neigh8
	    row = int(pos.imag)
		      ^^^
	NameError: name 'pos' is not defined. Did you mean: 'os'?
	$ python3 day4.py -c
	Guessing paste kind from your clipboard metadata...
	Unknown text pasted - continuing with previous sample input data
	=============> inputs/day4-samp.txt <=============
	10
	=============> inputs/day4-samp2.txt <=============
	239
	$ python3 day4.py -c
	Guessing paste kind from your clipboard metadata...
	Unknown text pasted - continuing with previous sample input data
	=============> inputs/day4-samp.txt <=============
	4
	=============> inputs/day4-samp2.txt <=============
	18
	$ python3 day4.py -c
	Guessing paste kind from your clipboard metadata...
	Getting data from clipboard...
	Storing clipboard contents as inputs/day4-test.txt...
	=============> inputs/day4-samp.txt <=============
	4
	=============> inputs/day4-samp2.txt <=============
	18
	=============> inputs/day4-test.txt <=============
	2336
	$ python3 day4.py -c
	=============> inputs/day4-samp.txt <=============
	4
	Traceback (most recent call last):
	  File "/kattis/aoc/aoc2024/day4.py", line 17, in <module>
	    a = [cmat.read(a) for a in cmat.neigh4diag(s)]
				       ^^^^^^^^^^^^^^^
	AttributeError: 'ComplexStringMatrix' object has no attribute 'neigh4diag'
	=============> inputs/day4-samp2.txt <=============
	18
	Traceback (most recent call last):
	  File "/kattis/aoc/aoc2024/day4.py", line 17, in <module>
	    a = [cmat.read(a) for a in cmat.neigh4diag(s)]
				       ^^^^^^^^^^^^^^^
	AttributeError: 'ComplexStringMatrix' object has no attribute 'neigh4diag'
	=============> inputs/day4-test.txt <=============
	2336
	Traceback (most recent call last):
	  File "/kattis/aoc/aoc2024/day4.py", line 17, in <module>
	    a = [cmat.read(a) for a in cmat.neigh4diag(s)]
				       ^^^^^^^^^^^^^^^
	AttributeError: 'ComplexStringMatrix' object has no attribute 'neigh4diag'
	$ python3 day4.py -c
	=============> inputs/day4-samp.txt <=============
	4
	0
	=============> inputs/day4-samp2.txt <=============
	18
	3
	=============> inputs/day4-test.txt <=============
	2336
	987
	$ python3 day4.py -c -p
	Guessing paste kind from your clipboard metadata...
	Getting data from clipboard...
	Storing clipboard contents as inputs/day4-samp3.txt...
	=============> inputs/day4-samp.txt <=============
	4
	0
	=============> inputs/day4-samp2.txt <=============
	18
	3
	=============> inputs/day4-samp3.txt <=============
	0
	3
	=============> inputs/day4-test.txt <=============
	2336
	987
	$ python3 day4.py -p
	Guessing paste kind from your clipboard metadata...
	It does not seem like you have copied Advent of Code input in your web browser.

	Please copy the sample data from https://adventofcode.com/2024/day/4
	or the test data from https://adventofcode.com/2024/day/4/input

	usage:

	  python3 day4.py         to run on AoC input copied from your web browser
	  python3 day4.py -       to run on input from stdin
	  python3 day4.py < FILE  to run on input from FILE
	  python3 day4.py NAME    to store clipboard contents and run on that input

	Input data will be cached as inputs/day4-*.txt for subsequent reuse.
	$ python3 day4.py
	=============> inputs/day4-samp.txt <=============
	4
	0
	=============> inputs/day4-samp2.txt <=============
	18
	['M', 'M', 'S', 'S']
	['M', 'S', 'M', 'S']

(...snip more printf-debugging...)

	$ python3 day4.py samp3
	=============> inputs/day4-samp3.txt <=============
	0
	Traceback (most recent call last):
	  File "/kattis/aoc/aoc2024/day4.py", line 21, in <module>
	    c += 1
	TypeError: can only concatenate str (not "int") to str
	$ python3 day4.py samp3
	=============> inputs/day4-samp3.txt <=============
	0
	9
	$ python3 day4.py -c
	=============> inputs/day4-samp.txt <=============
	4
	0
	=============> inputs/day4-samp2.txt <=============
	18
	9
	=============> inputs/day4-samp3.txt <=============
	0
	9
	=============> inputs/day4-test.txt <=============
	2336
	1831