2024d8 (120/101)
The cmat helper turned out to be useful here I think
but I was faffing around because the set of result locations
had the same variable name as the set of input locations
for a given character.

	$ python3 day8.py -c
	Guessing paste kind from your clipboard metadata...
	Getting data from clipboard...
	Storing clipboard contents as inputs/day8-samp.txt...
	=============> inputs/day8-samp.txt <=============
	Traceback (most recent call last):
	  File "/kattis/aoc/aoc2024/day8.py", line 11, in <module>
	    aa = 2*a-b
		 ~~~^~
	TypeError: unsupported operand type(s) for -: 'tuple' and 'tuple'
	$ python3 day8.py -c
	Guessing paste kind from your clipboard metadata...
	Getting data from clipboard...
	Input 'samp' already exists at inputs/day8-samp.txt
	=============> inputs/day8-samp.txt <=============
	Traceback (most recent call last):
	  File "/kattis/aoc/aoc2024/day8.py", line 14, in <module>
	    nodes.add(aa)
	    ^^^^^^^^^
	AttributeError: 'list' object has no attribute 'add'
	$ python3 day8.py -c
	Guessing paste kind from your clipboard metadata...
	Getting data from clipboard...
	Input 'samp' already exists at inputs/day8-samp.txt
	=============> inputs/day8-samp.txt <=============
	0
	$ python3 day8.py
	Guessing paste kind from your clipboard metadata...
	Unknown text pasted - continuing with previous sample input data
	=============> inputs/day8-samp.txt <=============
	(2+3j) (11+0j)
	(6+5j) (9-1j)
	(9+4j) (3+1j)
	7j (12-2j)
	(3+6j) (6+0j)
	(1+5j) (10+2j)
	(10+11j) (4+2j)
	(12+13j) (3+1j)
	(10+10j) (7+7j)
	0
	$ python3 day8.py
	Guessing paste kind from your clipboard metadata...
	Unknown text pasted - continuing with previous sample input data
	=============> inputs/day8-samp.txt <=============
	(2+3j) (11+0j)
	12 12
	(6+5j) (9-1j)
	12 12
	(9+4j) (3+1j)
	12 12
	7j (12-2j)
	12 12
	(3+6j) (6+0j)
	12 12
	(1+5j) (10+2j)
	12 12
	(10+11j) (4+2j)
	12 12
	(12+13j) (3+1j)
	12 12
	(10+10j) (7+7j)
	12 12
	0
	$ python3 day8.py
	Guessing paste kind from your clipboard metadata...
	Unknown text pasted - continuing with previous sample input data
	=============> inputs/day8-samp.txt <=============
	14
	$ python3 day8.py
	Guessing paste kind from your clipboard metadata...
	Getting data from clipboard...
	Storing clipboard contents as inputs/day8-test.txt...
	=============> inputs/day8-samp.txt <=============
	14
	=============> inputs/day8-test.txt <=============
	361
	$ python3 day8.py -c
	=============> inputs/day8-samp.txt <=============
	14
	=============> inputs/day8-test.txt <=============
	361
	$ python3 day8.py -c
	=============> inputs/day8-samp.txt <=============
	14
	34
	=============> inputs/day8-test.txt <=============
	361
	1249